### ISSUE TITLE
TODO: Integrate desk save button

### ISSUE THREAD

**Issue by LRahlff** [Mission-DMX/Project-Editor#41]
- [ ] The show editor should light up the X-Touch save button, when a change occurred.
- [ ] The show editor should disable the save button led, when a show file was loaded
- [ ] The show editor should disable the save button when the show file was saved
- [ ] Pressing the save button in the show editor should save the show file (opening a save dialog if, and only if, no file path is stored)

**Comment by Doralitze** [comment]
We also need to mark the button on the xtouch.
